name: phpunit

on:
  push:
    branches:
      - installer
  pull_request:
    branches:
      - installer

  workflow_dispatch:

defaults:
  run:
    working-directory: ./installer

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}, ${{ matrix.stability }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']
        os: ['ubuntu-latest']
        stability: ['prefer-lowest', 'prefer-stable']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_sqlite, sockets, grpc
          tools: pecl

      - name: Validate Composer
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer

      - name: Install Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute Tests
        run: vendor/bin/phpunit
